
title: The uEngine / Open Cloud Engine Team Blog
description: Web Developer from Somewhere
author: uEngine solutions
github: https://github.com/TheOpenCloudEngine
about: 오픈클라우드엔진 - 성공적 클라우드 서비스 구축을 위한 가장 빠른 방법
disqus_shortname: uengine-team-blog
google_analytics: 
avatar_url: https://user-images.githubusercontent.com/487999/28487613-3fb174b4-6ecf-11e7-9b73-b032cf57427b.png

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "https://twitter.com/agusmakmun6"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/summonagus"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/TheOpenCloudEngine"

share:
  twitter_username: 
  fb_appid: 

urls:
    - text: About Us
      url: /about/
    - text: Our Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://theopencloudengine.github.io/TheOpenCloudEngine.github.io-blog"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all